import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./ClientProvider";

export const metadata: Metadata = {
  title: "Hyperhire Menu App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        {children}
      </ClientProvider>
    </html>
  );
}
